quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=denis
quarkus.datasource.password=denis
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hospital

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true