quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=denis
quarkus.datasource.password=denis
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hospital

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8081

quarkus.oidc.auth-server-url=http://localhost:8080/realms/hospital
quarkus.oidc.client-id=hospital-client
quarkus.oidc.credentials.secret=g9neyuxdmQiC9RbSttQ6faD5TgY937jg
quarkus.oidc.application-type=service

%test.quarkus.http.port=8082

quarkus.rest-client.ip-client.url=https://api.ipify.org
quarkus.rest-client.timeapi-client.url=https://timeapi.io